DEFAULT_ENCODING = "cp1252"
FALLBACK_ENCODING = "utf8-lossy"
DEFAULT_CHUNK_SIZE = 100_000
DEFAULT_PREVIEW_ROWS = 20
DELIMITERS = [",", "|", "\t", ";"]
MULTILINE_CHARS = ",|\t;"
DEFAULT_LOG_LEVEL = "INFO"
